spring:
  application:
    name: open_notepad
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  cloud:
    gateway:
      routes:
        - id: api-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
  datasource:
    url: jdbc:sqlserver://pacipapa.database.windows.net:1433;database=pacipapaDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: backendService
    password: "@1c09d9dc8c164765784de6a64675b49c90e19c2e6da457fed1980845b72fafb7"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver